#!/usr/bin/env node
/**
 * scaffold-agent.mjs
 *
 * Scaffolds a new A.D.A.M. agent entry for use with the adam-server.
 *
 * Usage:
 *   node scripts/scaffold-agent.mjs --name "Sensing Agent" --capabilities "web-scraping,api-monitoring"
 *
 * Options:
 *   --name           Agent name (required)
 *   --description    Agent description
 *   --capabilities   Comma-separated capability tags
 *   --model          LLM model (default: gpt-4o-mini)
 *   --output         Output format: json | ts (default: json)
 */

import { parseArgs } from "node:util";

const { values } = parseArgs({
  options: {
    name: { type: "string" },
    description: { type: "string", default: "A new A.D.A.M. agent." },
    capabilities: { type: "string", default: "" },
    model: { type: "string", default: "gpt-4o-mini" },
    output: { type: "string", default: "json" },
  },
});

if (!values.name) {
  console.error("Error: --name is required");
  console.error(
    'Usage: node scripts/scaffold-agent.mjs --name "My Agent" --capabilities "sensing,api-monitoring"',
  );
  process.exit(1);
}

const id = `agent-${values.name
  .toLowerCase()
  .replace(/\s+/g, "-")
  .replace(/[^a-z0-9-]/g, "")}-${Date.now()}`;
const capabilities = values.capabilities
  ? values.capabilities
      .split(",")
      .map((c) => c.trim())
      .filter(Boolean)
  : [];

const agent = {
  id,
  name: values.name,
  description: values.description,
  capabilities,
  model: values.model,
  status: "idle",
  createdAt: new Date().toISOString(),
};

if (values.output === "ts") {
  console.log(`// Auto-generated by scaffold-agent.mjs
// Add this to the agents array in examples/adam-server/server.ts

{
  id: "${agent.id}",
  name: "${agent.name}",
  description: "${agent.description}",
  capabilities: [${capabilities.map((c) => `"${c}"`).join(", ")}],
  model: "${agent.model}",
  status: "idle",
  createdAt: "${agent.createdAt}",
},`);
} else {
  console.log(JSON.stringify(agent, null, 2));
}

console.error(
  `\n✅ Agent '${agent.name}' scaffolded (ID: ${agent.id})\n` +
    `   Add the above definition to examples/adam-server/server.ts in the agents[] array,\n` +
    `   or POST it to the MCP server via the register-agent tool.`,
);
